#!/usr/bin/env bash

if command -v go > /dev/null 2>&1; then
  echo "go already installed"
else
  sudo rm -rf /usr/local/go
  cd /tmp
  wget https://go.dev/dl/go1.24.4.linux-amd64.tar.gz
  sudo tar -C /usr/local -xzf go1.24.4.linux-amd64.tar.gz
  rm -rf go1.24.4.linux-amd64.tar.gz
fi
