#!/usr/bin/env bash

if command -v nvim > /dev/null 2>&1; then
  echo "neovim already installed"
else
  echo "installing neovim"
  cd /tmp
  wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz
  tar -xzf nvim-linux-x86_64.tar.gz
  sudo rm -rf /opt/nvim-nightly
  sudo mv nvim-linux-x86_64 /opt/nvim-nightly
  #symlink only the binary
  sudo ln -sf /opt/nvim-nightly/bin/nvim /usr/local/bin/nvim
fi
