#!/usr/bin/env bash

if command -v zsh >/dev/null 2>&1; then
  echo "zsh already installed"
else
  echo "installing zsh"
  sudo apt update
  sudo apt install -y zsh
fi

hash -r

if [ "$SHELL" != "$(which zsh)" ]; then
  echo "setting zsh as default shell (for next login)"
  chsh -s $(which zsh)
fi

if [ -d "$HOME/.oh-my-zsh" ]; then
  echo "ohmyzsh is already installed"
else
  echo "installing ohmyzsh"
  RUNZSH=no CHSH=no KEEP_ZSHRC=no sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
fi
